<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<RootNamespace>LSTools.DebuggerFrontend</RootNamespace>

		<LangVersion>14</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<AssemblyTitle>Debugger Frontend</AssemblyTitle>
		<Product>LSLib</Product>
		<Copyright>Copyright © Norbyte 2012-2018</Copyright>
		<Trademark></Trademark>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>

		<ComVisible>false</ComVisible>
		<Guid>31e71543-cbcf-43bb-af77-d210d548118e</Guid>

		<PublishTrimmed>true</PublishTrimmed>
		<PublishAot>true</PublishAot>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<PropertyGroup>
			<IsWindows>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))</IsWindows>

			<ExeExt Condition="'$(IsWindows)' == 'true'">.exe</ExeExt>
			<ExeExt Condition="'$(IsWindows)' != 'true'"></ExeExt>
		</PropertyGroup>
	</Target>
	
	<ItemGroup>
		<ProjectReference Include="..\LSLib\LSLib.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="LightProto" Version="1.3.2" />
		<PackageReference Include="Superpower" Version="3.2.1" />
		<PackageReference Include="System.CommandLine" Version="2.0.8" />
	</ItemGroup>
</Project>