<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>14</LangVersion>
		<PublishTrimmed>true</PublishTrimmed>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<PropertyGroup>
			<IsWindows>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))</IsWindows>

			<ExeExt Condition="'$(IsWindows)' == 'true'">.exe</ExeExt>
			<ExeExt Condition="'$(IsWindows)' != 'true'"></ExeExt>
		</PropertyGroup>
	</Target>
	<ItemGroup>
	  <PackageReference Include="Superpower" Version="3.2.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LSLib\LSLib.csproj" />
	</ItemGroup>

</Project>